<a href="https://colab.research.google.com/github/ivandenb/MAT-442-Fall-2024-/blob/main/1_2linearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.2 Linear Spaces


**1.2.1 Linear Combinations**
When vectors are multiplied by scalars and added together they are still within the same subspace

In [7]:
import numpy as np

# Create three vectors of dimension three with random integers
vector1 = np.random.randint(0, 10, size=3)
vector2 = np.random.randint(0, 10, size=3)
vector3 = np.random.randint(0, 10, size=3)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Vector 3:", vector3)


Vector 1: [7 2 6]
Vector 2: [4 7 0]
Vector 3: [1 8 6]


In [8]:
# Create scalars
scalar1 = 2
scalar2 = -1
scalar3 = 0.5

# Calculate the linear combination
linear_combination = scalar1 * vector1 + scalar2 * vector2 + scalar3 * vector3

print("Linear Combination:", linear_combination)

Linear Combination: [10.5  1.  15. ]


Checking to see if the vectors are linearly independent

In [17]:
#Function for checking dependence of three vectors based on determinant

def dependence_check(v1, v2, v3):
  matrix = np.stack((v1, v2, v3), axis = -1)
  det = np.linalg.det(matrix)
  if det == 0:
    print("the vectors are linearly dependent")
  else:
    print("the vectors are linearly independent")

In [18]:
#Using code to check the dependence of the vectors

dependence_check(vector1, vector2, vector3)


the vectors are linearly independent


Calulating the dimension of the previous matrix formed from the three vectors

In [22]:
# Create the 3x3 matrix from the three vectors
matrix = np.stack((vector1, vector2, vector3))

matrix

array([[7, 2, 6],
       [4, 7, 0],
       [1, 8, 6]])

In [31]:
import sympy as sp

matrix_rank = sp.Matrix(matrix).rank()
print("matrix rank:" , matrix_rank)


matrix rank: 3


Finding the column space of the matrix

In [38]:
matrix_column_space = sp.Matrix(matrix).columnspace()
print("matrix column space:")
matrix_column_space



matrix column space:


[Matrix([
 [7],
 [4],
 [1]]),
 Matrix([
 [2],
 [7],
 [8]]),
 Matrix([
 [6],
 [0],
 [6]])]

In [39]:
#make it look neater
a=[7,4,1]
b=[2,7,8]
c=[6,0,6]
print("The column space is:", a, b, c,)


The column space is: [7, 4, 1] [2, 7, 8] [6, 0, 6]


1.2.2 Orthogonality

Firstly an example of an orthonormal basis

In [8]:
print("3 by 3 Orthonormal basis:\n", np.identity(3, dtype = int))


3 by 3 Orthonormal basis:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


Now there will be an example of Cauchy-Schwarz

Cauchy-Schwarz: |⟨u, v⟩| ≤ ∥u∥∥v∥

In [13]:
# Generate two random vectors of size 3
vector4 = np.random.randint(-10,10,size=3)
vector5 = np.random.randint(-10,10,size=3)

print("Vector 1:", vector4)
print("Vector 2:", vector5)

Vector 1: [-5 -7  7]
Vector 2: [-2  5  8]


In [14]:
# Solving for the inner product
inner_product = np.dot(vector4, vector5)
print("Inner product:", inner_product)

Inner product: 31


In [16]:
# Calculate the norms of vector4 and vector5
norm_vector4 = np.linalg.norm(vector4)
norm_vector5 = np.linalg.norm(vector5)

print("Norm of Vector 1:", norm_vector4)
print("Norm of Vector 2:", norm_vector5)

Norm of Vector 1: 11.090536506409418
Norm of Vector 2: 9.643650760992955


In [26]:
#Compare the two values to prove true

if norm_vector4*norm_vector5 > inner_product:
  print("|⟨u, v⟩| ≤ ∥u∥∥v∥ is true")
else: print("Cauchy-Schwarz is not true")

|⟨u, v⟩| ≤ ∥u∥∥v∥ is true


Thus our example of Cauchy Schwarz rings true.