<a href="https://colab.research.google.com/github/ivandenb/MAT-442-Fall-2024-/blob/main/1_2linearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.2 Linear Spaces


**1.2.1 Linear Combinations**
When vectors are multiplied by scalars and added together they are still within the same subspace

In [7]:
import numpy as np

# Create three vectors of dimension three with random integers
vector1 = np.random.randint(0, 10, size=3)
vector2 = np.random.randint(0, 10, size=3)
vector3 = np.random.randint(0, 10, size=3)

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Vector 3:", vector3)


Vector 1: [7 2 6]
Vector 2: [4 7 0]
Vector 3: [1 8 6]


In [8]:
# Create scalars
scalar1 = 2
scalar2 = -1
scalar3 = 0.5

# Calculate the linear combination
linear_combination = scalar1 * vector1 + scalar2 * vector2 + scalar3 * vector3

print("Linear Combination:", linear_combination)

Linear Combination: [10.5  1.  15. ]


Checking to see if the vectors are linearly independent

In [17]:
#Function for checking dependence of three vectors based on determinant

def dependence_check(v1, v2, v3):
  matrix = np.stack((v1, v2, v3), axis = -1)
  det = np.linalg.det(matrix)
  if det == 0:
    print("the vectors are linearly dependent")
  else:
    print("the vectors are linearly independent")

In [18]:
#Using code to check the dependence of the vectors

dependence_check(vector1, vector2, vector3)


the vectors are linearly independent


Calulating the dimension of the previous matrix formed from the three vectors

In [22]:
# Create the 3x3 matrix from the three vectors
matrix = np.stack((vector1, vector2, vector3))

matrix

array([[7, 2, 6],
       [4, 7, 0],
       [1, 8, 6]])

In [31]:
import sympy as sp

matrix_rank = sp.Matrix(matrix).rank()
print("matrix rank:" , matrix_rank)


matrix rank: 3


Finding the column space of the matrix

In [38]:
matrix_column_space = sp.Matrix(matrix).columnspace()
print("matrix column space:")
matrix_column_space



matrix column space:


[Matrix([
 [7],
 [4],
 [1]]),
 Matrix([
 [2],
 [7],
 [8]]),
 Matrix([
 [6],
 [0],
 [6]])]

In [39]:
#make it look neater
a=[7,4,1]
b=[2,7,8]
c=[6,0,6]
print("The column space is:", a, b, c,)


The column space is: [7, 4, 1] [2, 7, 8] [6, 0, 6]


1.2.2 Orthogonality

Firstly an example of an orthonormal basis

In [8]:
print("3 by 3 Orthonormal basis:\n", np.identity(3, dtype = int))


3 by 3 Orthonormal basis:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


Now there will be an example of Cauchy-Schwarz

Cauchy-Schwarz: |⟨u, v⟩| ≤ ∥u∥∥v∥

In [13]:
# Generate two random vectors of size 3
vector4 = np.random.randint(-10,10,size=3)
vector5 = np.random.randint(-10,10,size=3)

print("Vector 1:", vector4)
print("Vector 2:", vector5)

Vector 1: [-5 -7  7]
Vector 2: [-2  5  8]


In [14]:
# Solving for the inner product
inner_product = np.dot(vector4, vector5)
print("Inner product:", inner_product)

Inner product: 31


In [16]:
# Calculate the norms of vector4 and vector5
norm_vector4 = np.linalg.norm(vector4)
norm_vector5 = np.linalg.norm(vector5)

print("Norm of Vector 1:", norm_vector4)
print("Norm of Vector 2:", norm_vector5)

Norm of Vector 1: 11.090536506409418
Norm of Vector 2: 9.643650760992955


In [26]:
#Compare the two values to prove true

if norm_vector4*norm_vector5 > inner_product:
  print("|⟨u, v⟩| ≤ ∥u∥∥v∥ is true")
else: print("Cauchy-Schwarz is not true")

|⟨u, v⟩| ≤ ∥u∥∥v∥ is true


Thus our example of Cauchy Schwarz rings true.

1.2.3 Gram Schmidt Process

First generating 3 random linearly independent vectors

In [68]:
# Create three vectors of dimension three with random integers
vector6 = np.random.randint(0, 10, size=3)
vector7 = np.random.randint(0, 10, size=3)
vector8 = np.random.randint(0, 10, size=3)


def dependence_check(v1, v2, v3):
  matrix = np.stack((v1, v2, v3), axis = -1)
  det = np.linalg.det(matrix)
  if det == 0:
    print("the vectors are linearly dependent")
  else:
    print("the vectors are linearly independent")

print("\n", vector6, "\n", vector7, "\n", vector8)

dependence_check(vector6, vector7, vector8)


 [6 2 4] 
 [4 7 6] 
 [7 7 6]
the vectors are linearly independent


Then performing Gram-Schmidt

In [72]:
#Solve Gram Schmidt

#Let u1=v1
u1=vector6

#Let u2=v2-(<u1,v1>/<u1,u1>)u1

u2=vector7-(np.dot(u1,vector7)/np.dot(u1,u1))*u1

#solve u3

u3=vector8-(np.dot(u1,vector8)/np.dot(u1,u1))*u1-(np.dot(u2,vector8)/np.dot(u2,u2))*u2

#Now normalize the vectors

e1=u1/np.linalg.norm(u1)
e2=u2/np.linalg.norm(u2)
e3=u3/np.linalg.norm(u3)

#print the vectors
print("\n", e1, "\n", e2, "\n", e3)


 [0.80178373 0.26726124 0.53452248] 
 [-0.46461006  0.84132091  0.27625463] 
 [ 0.37587279  0.46984099 -0.79872968]


Thus the Gram-Schmidt process is complete

1.2.4 Eigen Vectors

Solving an Eigen vector example given a random matrix of 3 by 3

In [80]:
# Generate a 3x3 matrix of random integers
matrix1 = np.random.randint(0, 10, size=(3, 3))

print(matrix1)

[[9 3 6]
 [6 8 8]
 [2 9 9]]


In [81]:
# Calculate eigenvalues and eigenvectors of matrix1

eigenvalues, eigenvectors = np.linalg.eig(matrix1)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [20.18660621  4.58048839  1.2329054 ]
Eigenvectors:
 [[-0.49064151 -0.76216996 -0.35779279]
 [-0.63398097 -0.14090626 -0.56325884]
 [-0.59777842  0.63185629  0.74479782]]
