<a href="https://colab.research.google.com/github/ivandenb/MAT-442-Fall-2024-/blob/main/HW1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.3 Linear Regression**

1.3.1 QR Decomposition

First use generate random linearly independent vectors

In [ ]:
# import
import numpy as np

# generate the vectors
# Create three vectors of dimension three with random integers
vector1 = np.random.randint(0, 10, size=3)
vector2 = np.random.randint(0, 10, size=3)
vector3 = np.random.randint(0, 10, size=3)


def dependence_check(v1, v2, v3):
  matrix = np.stack((v1, v2, v3), axis = -1)
  det = np.linalg.det(matrix)
  if det == 0:
    print("the vectors are linearly dependent")
  else:
    print("the vectors are linearly independent")

print("\n", vector1, "\n", vector2, "\n", vector3)

dependence_check(vector1, vector2, vector3)


 [6 2 7] 
 [7 0 6] 
 [9 3 7]
the vectors are linearly independent


Then perform Gram-Schmidt to get Q

In [ ]:
#Solve Gram Schmidt

#Let u1=v1
u1=vector1

#Let u2=v2-(<u1,v1>/<u1,u1>)u1

u2=vector2-(np.dot(u1,vector2)/np.dot(u1,u1))*u1

#solve u3

u3=vector3-(np.dot(u1,vector3)/np.dot(u1,u1))*u1-(np.dot(u2,vector3)/np.dot(u2,u2))*u2

#Now normalize the vectors

e1=u1/np.linalg.norm(u1)
e2=u2/np.linalg.norm(u2)
e3=u3/np.linalg.norm(u3)

#print the vectors
print("\n", e1, "\n", e2, "\n", e3)


 [0.63599873 0.21199958 0.74199852] 
 [ 0.5591046  -0.78932414 -0.25371133] 
 [ 0.53189065  0.57621487 -0.62053909]


Then create the R matrix

In [ ]:
# Then create the R matrix
Q = np.stack((e1, e2, e3), axis=-1)
R = np.zeros((3,3))

R[0,0] = np.dot(vector1,e1)
R[0,1] = np.dot(vector2,e1)
R[0,2] = np.dot(vector3,e1)
R[1,1] = np.dot(vector2,e2)
R[1,2] = np.dot(vector3,e2)
R[2,2] = np.dot(vector3,e3)

#print the matrices

print("\nQ matrix:\n", Q)
print("\nR matrix:\n", R)


Q matrix:
 [[ 0.63599873  0.5591046   0.53189065]
 [ 0.21199958 -0.78932414  0.57621487]
 [ 0.74199852 -0.25371133 -0.62053909]]

R matrix:
 [[ 9.43398113  8.90398219 11.55397689]
 [ 0.          2.39146422  0.88798966]
 [ 0.          0.          2.17188682]]


Then check the work by multiplying q and r together and check to see if it is equal to the original matrix

In [ ]:
#Multply Q and R

multiplied_matrix = np.dot(Q,R)

#round the multiplied matrix into integers

rounded_matrix = np.round(multiplied_matrix).astype(int)


#print the matrices
original_matrix = np.stack((vector1, vector2, vector3), axis = -1)
multiplied_matrix = np.dot(Q,R)
print("\noriginal matrix:\n", original_matrix)
print("\nmultiplied matrix:\n", rounded_matrix)

#check to see if they are equal
if np.array_equal(rounded_matrix, original_matrix):
  print("THE MATRICES ARE EQUAL")
else:
  print("The Matrices Are Not Equal")


original matrix:
 [[6 7 9]
 [2 0 3]
 [7 6 7]]

multiplied matrix:
 [[6 7 9]
 [2 0 3]
 [7 6 7]]
THE MATRICES ARE EQUAL


And thus the QR decompisition rings true

1.3.2 Least Squares Problem

Try to solve the equation Ax=b where A is a n by m matrix where n>m.  We want find the minimum values for ||Ax-b||.  We will do this using QR decompisiton.

In [ ]:

# Generate a 3x2 matrix of random integers
matrix1 = np.random.randint(-10, 10, size=(3, 2))

print("A=\n", matrix1)

#generate a 3 by 1 vector labeled b
b = np.random.randint(-10, 10, size=(3, 1))

print("\nb=\n", b)

A=
 [[-5 -5]
 [ 5  5]
 [-2  6]]

b=
 [[-2]
 [-3]
 [ 9]]


Now do the QR decomposition of A

In [ ]:
#Solve Gram Schmidt

vector4=matrix1[:,0]
vector5=matrix1[:,1]


#Let u3=v3
u4=vector4

#Let u2=v2-(<u1,v1>/<u1,u1>)u1

u5=vector5-(np.dot(u4,vector5)/np.dot(u4,u4))*u4

#Now normalize the vectors

e4=u4/np.linalg.norm(u4)
e5=u5/np.linalg.norm(u5)



# Then create the R matrix
Q = np.stack((e4, e5), axis=-1)
R = np.zeros((2,2))

R[0,0] = np.dot(vector4,e4)
R[0,1] = np.dot(vector5,e4)
R[1,1] = np.dot(vector5,e5)


#print the matrices

print("\nQ matrix:\n", Q)
print("\nR matrix:\n", R)

multiplied_matrix = np.dot(Q,R)

#round the multiplied matrix into integers

rounded_matrix = np.round(multiplied_matrix).astype(int)


#print the matrices
original_matrix = np.stack((vector4, vector5), axis = -1)
multiplied_matrix = np.dot(Q,R)
print("\noriginal matrix:\n", original_matrix)
print("\nmultiplied matrix:\n", rounded_matrix)

#check to see if they are equal
if np.array_equal(rounded_matrix, original_matrix):
  print("THE MATRICES ARE EQUAL")
else:
  print("The Matrices Are Not Equal")


Q matrix:
 [[-0.68041382 -0.19245009]
 [ 0.68041382  0.19245009]
 [-0.27216553  0.96225045]]

R matrix:
 [[7.34846923 5.17114501]
 [0.         7.69800359]]

original matrix:
 [[-5 -5]
 [ 5  5]
 [-2  6]]

multiplied matrix:
 [[-5 -5]
 [ 5  5]
 [-2  6]]
THE MATRICES ARE EQUAL


After checking that the QR was done correctly, then check that Rx*=(Q^T)b

In [ ]:
# Calculate Q transpose
Q_transpose = np.transpose(Q)

# Multiply Q transpose times b
Qb = np.dot(Q_transpose, b)

print("\nQ transpose times b:\n", Qb, "\n")


Q transpose times b:
 [[-3.12990356]
 [ 8.46780395]] 



Solve for x

In [ ]:
# Solve for x in Rx = Qb
x = np.linalg.solve(R, Qb)

print("Solution x:\n", x)

Solution x:
 [[-1.2]
 [ 1.1]]


Thus we have our solution of least squares.

1.3.3 Linear Regression

This is exacly what was demonstrated in the code above.  By using least squares we were able to find the linear regression of a group of functions in the form of Ax=b.