<a href="https://colab.research.google.com/github/ivandenb/MAT-442-Fall-2024-/blob/main/Hw1_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Principal Component **Analysis**

1.4.1 Singular Value Decompisition

We will start by generating a 4 by 3 matrix to perform Single Value decomposition on.

In [68]:
# import

import numpy as np

# Generate a 4x3 matrix with random integers with values from -10 to 10
matrix1 = np.random.randint(-10, 10, size=(3, 3))

print("\n", matrix1)



 [[ 7  2  2]
 [-9  8 -8]
 [-9  6  6]]


Then to perform single value decomposition on the function

In [69]:
#Multiply the matrix by its own transpose

A=np.dot(matrix1,matrix1.T)

print("\n", A)


 [[ 57 -63 -39]
 [-63 209  81]
 [-39  81 153]]


In [70]:

# Find the eigenvalues and eigenvectors of matrix A
eigenvalues, eigenvectors = np.linalg.eig(A)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 [290.16228167  33.2157226   95.62199573]

Eigenvectors:
 [[ 0.30241172 -0.95077219  0.06767128]
 [-0.78061928 -0.28778003 -0.55481185]
 [-0.54697412 -0.1149561   0.82921915]]


In [71]:
#SOlve for u1,u2,u3 from the eigenvectors
u1=np.dot(A,eigenvectors[:,0])/np.linalg.norm(np.dot(A,eigenvectors[:,0]))
u2=np.dot(A,eigenvectors[:,1])/np.linalg.norm(np.dot(A,eigenvectors[:,1]))
u3=np.dot(A,eigenvectors[:,2])/np.linalg.norm(np.dot(A,eigenvectors[:,2]))
#u4=np.dot(A,eigenvectors[:,3])/np.linalg.norm(np.dot(A,eigenvectors[:,3]))

#print the U vectors
print("\n", u1)
print("\n", u2)
print("\n", u3)
#print("\n", u4)



 [ 0.30241172 -0.78061928 -0.54697412]

 [-0.95077219 -0.28778003 -0.1149561 ]

 [ 0.06767128 -0.55481185  0.82921915]


In [72]:
# Stack the U vectors
U = np.column_stack((u1, u2, u3))
print("\nStacked U vectors:\n", U.T)


Stacked U vectors:
 [[ 0.30241172 -0.78061928 -0.54697412]
 [-0.95077219 -0.28778003 -0.1149561 ]
 [ 0.06767128 -0.55481185  0.82921915]]


In [73]:
#Multiply U.T A and eigenvetors
B=np.dot(U.T, A,)
S=np.dot(B, eigenvectors)
print("\n", B)


 [[  87.74847333 -226.50627193 -158.71125955]
 [ -31.58058523   -9.55882149   -3.8183499 ]
 [   6.47086278  -53.05221679   79.29159033]]


In [74]:
#round the matrix to 3 decimals
S=np.round(S, decimals=3)
print("\n", S)


 [[290.162  -0.     -0.   ]
 [ -0.     33.216  -0.   ]
 [ -0.     -0.     95.622]]


In [75]:
X=np.dot(U, S)
print("\n", np.dot(X, eigenvectors.T))


 [[ 57.00022502 -62.99985777 -38.99992285]
 [-62.99985777 208.99985265  80.99988695]
 [-38.99992285  80.99988695 152.99992233]]


In [83]:

Soln=np.rint(np.dot(X, eigenvectors.T))
print("\n", Soln)


 [[ 57. -63. -39.]
 [-63. 209.  81.]
 [-39.  81. 153.]]


Thus we have returned our original matrix and performed single value decomposition on the matrix

1.4.2 Low rank matrix approximations

In [98]:
# Example matrix (replace with your actual matrix)
original_matrix = np.random.randint(-10, 10, size=(3, 3))

#print matrix

print("Original Matrix:\n", original_matrix)




Original Matrix:
 [[ -2   1   7]
 [  2   7  -7]
 [-10   9   7]]


We will then choose a rank of 2 and do an example of a low rank approximation of the matrix given along with using single value decomposition.(this time I will use a simple python algorithm and not generate the svd from scratch as in 1.4.1)

In [99]:
# Perform SVD
U, S, V = np.linalg.svd(original_matrix)

# Create the low-rank approximation
S_approximate = np.zeros((3, 3))
S_approximate[:2, :2] = np.diag(S[:2])
low_rank_approx = U @ S_approximate @ V

print("\nLow-Rank Approximation:\n".format(2), low_rank_approx)



Low-Rank Approximation:
 [[-3.72625018  0.09860197  5.93031676]
 [ 1.20465524  6.58469392 -7.49284105]
 [-9.41878673  9.3034928   7.36015295]]


And there is an example of a low rank approximation.

1.4.3 Principal component analysis

First Some sample data will be generated

In [106]:
# Sample data
data = np.random.randint(-10, 10, size=(3,3))

print("sample data: \n", data)

sample data: 
 [[ 8  0  3]
 [-7  8  4]
 [ 3  0 -9]]


The center the date using the mean

In [108]:
#Center the data
mean = np.mean(data, axis=0)
centered_data = data - mean

print("centered data: \n", centered_data)

centered data: 
 [[ 6.66666667 -2.66666667  3.66666667]
 [-8.33333333  5.33333333  4.66666667]
 [ 1.66666667 -2.66666667 -8.33333333]]


Then calculate the covariance matrix using np.cov as already coded in numpy

In [110]:
#Calculate the covariance matrix
covariance_matrix = np.cov(centered_data, rowvar=False)

print("\ncovariance matrix:\n", covariance_matrix)


Covariance Matrix:
 [[ 58.33333333 -33.33333333 -14.16666667]
 [-33.33333333  21.33333333  18.66666667]
 [-14.16666667  18.66666667  52.33333333]]


Find the eigenvalues and vectors

In [112]:
# Find the eigenvalues and eigenvectors
eigenvalues1, eigenvectors1 = np.linalg.eig(covariance_matrix)

print("\nEigenvalues:\n", eigenvalues1)
print("\nEigenvectors:\n", eigenvectors1)


Eigenvalues:
 [9.05475729e+01 4.14524271e+01 4.91801235e-15]

Eigenvectors:
 [[-0.71875009  0.52800069 -0.45234232]
 [ 0.48143131 -0.09143665 -0.87170135]
 [ 0.50161958  0.84430718  0.18847597]]


Sort the eigenvalues and eigenvectors

In [117]:
#sort the eigenvalues and eigenvectors to prepare for principal components

sorted_indices = np.argsort(eigenvalues1)[::-1]
eigenvalues2 = eigenvalues1[sorted_indices]
eigenvectors2 = eigenvectors1[:, sorted_indices]

print("\nEigenvalues:\n", eigenvalues2)
print("\nEigenvectors:\n", eigenvectors2)


Eigenvalues:
 [9.05475729e+01 4.14524271e+01 4.91801235e-15]

Eigenvectors:
 [[-0.71875009  0.52800069 -0.45234232]
 [ 0.48143131 -0.09143665 -0.87170135]
 [ 0.50161958  0.84430718  0.18847597]]


Find the 2 principal components

In [118]:
#Find 2 principal components

num_components = 2
principal_components = eigenvectors[:, :num_components]

print("\nPrincipal Components:\n", principal_components)


Principal Components:
 [[ 0.39665213 -0.91758149]
 [-0.9152121  -0.39304395]
 [-0.07109076 -0.05967129]]


Then using loadings show the projected data

In [119]:
# Project the data onto the principal components
projected_data = centered_data @ principal_components

print("\nProjected Data:\n", projected_data)


Projected Data:
 [[ 4.82424703 -5.28788747]
 [-8.51832248  5.27181206]
 [ 3.69407545  0.01607541]]


And thus the principal component analysis has been completed on a random 3 by 3 matrix of data.